default_index:
    path: /
    defaults: { _controller: App\Controller\DefaultController::index }

ebay_index:
    path: /ebay/
    defaults: { _controller: App\Controller\EbayController::index }
    methods: [GET]

ebay_api_search_advanced:
    path: /ebay/ebay-search-advanced
    defaults: { _controller: App\Controller\EbayController::searchAdvanced }
    methods: [GET]

ebay_seller_item_add:
    path: /ebay/ebay-seller-item-add
    defaults: { _controller: App\Controller\EbayController::sellerItemAdd }
    methods: [GET]