default_index:
    path: /
    defaults: { _controller: App\Controller\DefaultController::index }

ebay_api_search_advanced:
    path: /ebay-search-advanced
    defaults: { _controller: App\Controller\DefaultController::ebayApi }
    methods: [GET]

ebay_seller_item_add:
    path: /ebay-seller-item-add
    defaults: { _controller: App\Controller\EbayController::sellerItemAdd }
    methods: [GET]